(define mci (getCurPrevOutParam "restrictmci.mci"))
(if (hasCurPrevOutParam "restrictmci.mci")
    (if (> (getCurrentMCI) (Int mci))
        (define res 1)
        (define res 0)
    )
    (define res 0)
)
(print "Result of Contract[RestrictMCI]: ")
(println res)